"""
Zip Packager — BrandForge AI
Collects all generated assets, writes brand_profile.json + README,
and packages everything into a named ZIP file.

Asset paths match asset_generator.py output:
  outputs/{job_id}/assets/flyer.pdf
  outputs/{job_id}/assets/social_card.png
  outputs/{job_id}/assets/email_*.html
  outputs/{job_id}/assets/ad_copy.pdf
"""

from __future__ import annotations

import json
import os
import zipfile
from datetime import datetime
from pathlib import Path

from job_manager import job_manager
from pipeline.state import BrandForgeState

OUTPUT_BASE_DIR = Path(os.getenv("OUTPUT_DIR", "./outputs"))


# ---------------------------------------------------------------------------
# Brand profile builder
# ---------------------------------------------------------------------------

def _build_brand_profile(state: dict) -> dict:
    """
    Build the brand_profile.json that goes into the ZIP.
    Includes all fields — old and new — from the full pipeline state.
    """
    profile = state.get("brand_profile", {}) or {}
    copy    = state.get("copy_output") or {}

    # Colors — handle both dataclass and dict
    colors = (
        state.get("brand_colors")
        or profile.get("brand_colors")
        or profile.get("colors")
        or {}
    )
    if hasattr(colors, "__dict__"):
        colors = dict(colors.__dict__)
    elif not isinstance(colors, dict):
        colors = {}

    def _sv(key: str, fallback=None):
        """State value — top-level first, then brand_profile fallback."""
        val = state.get(key)
        if val not in (None, "", [], {}):
            return val
        return profile.get(key, fallback)

    return {
        # Core identity
        "brand_name":            _sv("brand_name", ""),
        "brand_category":        _sv("brand_category", ""),
        "brand_tone":            _sv("brand_tone", ""),
        "target_audience":       _sv("target_audience", ""),
        "brand_promise":         _sv("brand_promise", ""),
        "competitive_edge":      _sv("competitive_edge", ""),
        "usps":                  _sv("usps", []),
        "key_products_services": _sv("key_products_services", []),
        "brand_voice_examples":  _sv("brand_voice_examples", []),

        # Extended intelligence (new fields)
        "emotional_benefit":     _sv("emotional_benefit", ""),
        "brand_archetype":       _sv("brand_archetype", ""),
        "visual_style":          _sv("visual_style", ""),
        "pricing_model":         _sv("pricing_model", ""),
        "content_themes":        _sv("content_themes", []),
        "industry_language":     _sv("industry_language", []),

        # Colors
        "brand_colors": colors,

        # Copy highlights
        "tagline":               copy.get("tagline") or profile.get("tagline", ""),
        "elevator_pitch":        copy.get("elevator_pitch", ""),
        "usp_titles":            copy.get("usp_titles", []),

        # Meta
        "source_url":            state.get("url", ""),
        "generated_at":          datetime.utcnow().isoformat() + "Z",
        "generator":             "BrandForge AI",
    }


def _build_readme(state: dict, brand_profile: dict) -> str:
    """Generate a human-readable README for the ZIP."""
    name      = brand_profile.get("brand_name", "Your Brand")
    tagline   = brand_profile.get("tagline", "")
    pitch     = brand_profile.get("elevator_pitch", "")
    usps      = brand_profile.get("usps", [])
    url       = brand_profile.get("source_url", "")
    generated = brand_profile.get("generated_at", "")

    usp_lines = "\n".join(f"  • {u}" for u in usps[:5]) if usps else "  • See brand_profile.json"

    return f"""BrandForge AI — Brand Kit
{'=' * 50}
Brand:     {name}
Tagline:   {tagline}
Source:    {url}
Generated: {generated}

About {name}:
{pitch}

Key Strengths:
{usp_lines}

{'=' * 50}
FILES IN THIS KIT:
{'=' * 50}

flyer.pdf
  Print-ready A4 brand flyer.
  Use for pitch decks, trade shows, handouts.

social_card.png
  1080x1080px social media card.
  Ready for Instagram, LinkedIn, Twitter/X.

email_welcome.html
  Welcome email campaign — for new subscribers/users.
  Open in browser or paste into your email platform.

email_promo.html
  Promotional email campaign — offers and announcements.

email_reengagement.html
  Re-engagement email — bring back inactive contacts.

ad_copy.pdf
  Performance ad copy kit:
  - Attention headlines (5 variants)
  - Body copy (3 angles: pain, aspiration, proof)
  - CTAs (3 variants)
  - Google RSA headlines (30 char) + descriptions (90 char)
  - Meta/Facebook primary text
  - LinkedIn ad (intro + body + CTA)
  - Social hooks (3 scroll-stopping openers)

brand_profile.json
  Full extracted brand profile as structured JSON.
  Use as input for other tools or your CMS.

{'=' * 50}
Generated by BrandForge AI
{'=' * 50}
"""


# ---------------------------------------------------------------------------
# Main node
# ---------------------------------------------------------------------------

def zip_packager_node(state: BrandForgeState) -> dict:
    job_id = state.get("job_id", "unknown")

    job_manager.emit(job_id, {
        "type": "zip_packager",
        "stage": "zip_packager",
        "status": "running",
        "message": "Packaging brand kit ZIP...",
    })

    job_dir   = OUTPUT_BASE_DIR / job_id
    asset_dir = job_dir / "assets"
    job_dir.mkdir(parents=True, exist_ok=True)
    asset_dir.mkdir(parents=True, exist_ok=True)

    # --- Write brand_profile.json ---
    brand_profile = _build_brand_profile(state)
    profile_path  = job_dir / "brand_profile.json"
    try:
        with open(profile_path, "w", encoding="utf-8") as f:
            json.dump(brand_profile, f, indent=2, ensure_ascii=False)
        print(f"[zip_packager] brand_profile.json written: {profile_path}")
    except Exception as e:
        print(f"[zip_packager] brand_profile.json write error: {e}")

    # --- Write README ---
    readme_path = job_dir / "README.txt"
    try:
        readme_path.write_text(_build_readme(state, brand_profile), encoding="utf-8")
    except Exception as e:
        print(f"[zip_packager] README write error: {e}")

    # --- Collect asset files ---
    # Asset generator writes to outputs/{job_id}/assets/
    asset_files = [
        ("flyer.pdf",               asset_dir / "flyer.pdf"),
        ("social_card.png",         asset_dir / "social_card.png"),
        ("email_welcome.html",      asset_dir / "email_welcome.html"),
        ("email_promo.html",        asset_dir / "email_promo.html"),
        ("email_reengagement.html", asset_dir / "email_reengagement.html"),
        ("ad_copy.pdf",             asset_dir / "ad_copy.pdf"),
    ]
    # brand_profile and README live in job_dir
    meta_files = [
        ("brand_profile.json", profile_path),
        ("README.txt",         readme_path),
    ]

    # --- Build ZIP ---
    brand_name_slug = (
        brand_profile.get("brand_name", "brand")
        .replace(" ", "_")
        .replace("/", "-")
        [:20]
    )
    zip_filename = f"brandforge_kit_{brand_name_slug}_{job_id[:8]}.zip"
    zip_path = job_dir / zip_filename

    missing: list[str] = []
    included: list[str] = []

    try:
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zipf:
            for arcname, path in asset_files + meta_files:
                if path.exists():
                    zipf.write(path, arcname)
                    included.append(arcname)
                else:
                    missing.append(arcname)
                    print(f"[zip_packager] WARNING: {arcname} not found at {path}")

        print(
            f"[zip_packager] ZIP created: {zip_path} | "
            f"included={len(included)} | missing={len(missing)}"
        )
        if missing:
            print(f"[zip_packager] Missing files: {missing}")

    except Exception as e:
        print(f"[zip_packager] ZIP creation failed: {e}")
        zip_path = job_dir / "brandforge_empty.zip"

    message = (
        f"Brand kit packaged — {len(included)} files | "
        f"{zip_filename}"
    )
    if missing:
        message += f" | {len(missing)} missing: {', '.join(missing)}"

    event = {
        "type":    "zip_packager",
        "stage":   "zip_packager",
        "status":  "done",
        "message": message,
    }
    job_manager.emit(job_id, event)

    return {
        "zip_path": str(zip_path),
        "events":   [event],
    }